"""AI agents for blueprint generation and validation.

This module defines agents for creating and validating run.sh files
based on technology specifications.
"""

from __future__ import annotations as _annotations

import atexit

from ddgs import DDGS
from pydantic_ai import Agent
from pydantic_ai.common_tools.duckduckgo import duckduckgo_search_tool

from models import Technology
from tools import (
    create_directory,
    example_for_run_sh,
    generate_run_sh,
    instructions,
    system_prompt,
    technology_stack,
    show_invalid_run_sh,
)


def create_ddgs_client():
    """Create a DuckDuckGo search client with automatic cleanup.

    Returns:
        DDGS: A configured DuckDuckGo search client instance.
    """
    client = DDGS()
    # Register cleanup function
    atexit.register(lambda: client.close() if hasattr(client, "close") else None)
    return client


blueprint_agent = Agent(
    "google-gla:gemini-2.5-flash",
    deps_type=Technology,
    output_type=[generate_run_sh],
    system_prompt=[system_prompt(), example_for_run_sh()],
    instructions=[instructions()],
    tools=[duckduckgo_search_tool(create_ddgs_client()), create_directory, technology_stack],
)

validator_agent = Agent(
    "google-gla:gemini-2.5-flash",
    deps_type=Technology,
    output_type=[generate_run_sh],
    system_prompt="You are an expert DevOps, with vast knowledge in OS and Technology. You have meta-cognitive skills to think step by step and give Precise Correct and Concise answers. Your core job is to validate the run.sh file generated by blueprint agent. Based on the run.sh file generated by blueprint agent, validate it and if it is correct, return 'valid' else return 'invalid'. ",
    instructions="""
    1. Check log message provided by blueprint agent.Provided as User Prompt.
    2. Deeply Inspect the invalid_run_sh file generated by blueprint agent and validate it.
    3. Use duckduckgo search tool to search for the error.
    2. Seek what error occurred, you can use duckduckgo search tool to search for the error.
    3. Try to fix the error and again call generate_run_sh tool.
    THE FILE YOU GOT HAVE SOME ERROR , INSPECT IT AGAINST LOG MESSAGE TO FIX THE ERROR.
    """,
    tools=[duckduckgo_search_tool(create_ddgs_client()), show_invalid_run_sh],
)
